remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark" or nil (default)
color_scheme: "dark"
search_enabled: true
title: "AMUSE"
description: AMUSE provides a Python interface to many astrophysical simulation codes
# logo: images/amuse-logo.png
show_downloads: true


aux_links:
    "AMUSE main github page":
        - "https://github.com/amusecode/amuse"
    "Documentation":
        - "https://amuse.readthedocs.io/en/latest/"
    "Installation":
        - "https://amuse.readthedocs.io/en/latest/install/howto-install-AMUSE.html"
